### ISSUE TITLE
[Bug]: Pivotal Import Missing data/ files

### ISSUE THREAD

**Issue by davydotcom** [useshortcut/api-cookbook#61]
### Do I have the most recent api-cookbook code?

- [X] I am using the latest code available on the `main` branch of the api-cookbook repo.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

It appears the README documentation for pivotal import is referencing `data/users.csv` and `data/priorities.csv` but neither of these files exist. This may becausing an import error as config or state mappings are also missing

```
Traceback (most recent call last):
  File "/Users/tommy/Documents/pivotal/git/api-cookbook/pivotal-import/pivotal_import.py", line 554, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/Users/tommy/Documents/pivotal/git/api-cookbook/pivotal-import/pivotal_import.py", line 545, in main
    process_pt_csv_export(ctx, cfg["pt_csv_file"], entity_collector)
  File "/Users/tommy/Documents/pivotal/git/api-cookbook/pivotal-import/pivotal_import.py", line 496, in process_pt_csv_export
    entity = build_entity(ctx, row_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tommy/Documents/pivotal/git/api-cookbook/pivotal-import/pivotal_import.py", line 243, in build_entity
    d["workflow_state_id"] = ctx["workflow_config"][pt_state]
                             ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'started'
make: *** [import] Error 1
```

### Expected Behavior

Import to function

### Minimal Reproducible Example

fresh git clone of project

### Environment

- Operating system: MacOS
- Python/JavaScript version: 3.10

**Comment by semperos** [comment]
Hi @davydotcom thanks for the bug report!

The `data/users.csv` and `data/priorities.csv` files get written on the fly as initialization occurs, we should make that clearer in the README, I'll add that to my todos.

I've just followed the following steps on a fresh clone and see the output printed below. What different steps can I take to try to reproduce what you're seeing on your end?

**1. Initial `make import` with nothing set up**

```shell
$ git clone https://github.com/useshortcut/api-cookbook.git
$ cd api-cookbook/
$ make import
./setup
Creating a virtualenv for this project...
Pipfile: /Users/dlg/tmp/another-tmp/api-cookbook/pivotal-import/Pipfile
Using /Users/dlg/.pyenv/versions/3.10.12/bin/python3 (3.10.12) to create virtualenv...
⠸ Creating virtual environment...created virtual environment CPython3.10.12.final.0-64 in 313ms
  creator CPython3Posix(dest=/Users/dlg/.local/share/virtualenvs/pivotal-import-YGJ54GsU, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/dlg/Library/Application Support/virtualenv)
    added seed packages: pip==24.0, setuptools==69.2.0, wheel==0.43.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/dlg/.local/share/virtualenvs/pivotal-import-YGJ54GsU
Installing dependencies from Pipfile.lock (446085)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

[Success] Python dependencies installed.

You can now either run the initialization script directly:

    pipenv run python initialize.py

Or you can enter a shell with all dependencies loaded,
so you don't have to prepend commands with 'pipenv run':

    pipenv shell
    python initialize.py

Once you're finished, you can run 'exit' to exit the
pipenv shell and return to your normal shell.
pipenv run python initialize.py
Problems:
 - You must define a SHORTCUT_API_TOKEN environment variable with your Shortcut API token.
 - Your Pivotal Tracker project export must be located at data/pivotal_export.csv
make: *** [initialize] Error 1
```

**2. Get a token defined and put my Pivotal export in place**

```shell
$ export SHORTCUT_API_TOKEN="_redacted_"
$ cp ~/Downloads/pivotal_export.csv ./data/pivotal_export.csv
$ make import
./setup
Installing dependencies from Pipfile.lock (446085)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

[Success] Python dependencies installed.

You can now either run the initialization script directly:

    pipenv run python initialize.py

Or you can enter a shell with all dependencies loaded,
so you don't have to prepend commands with 'pipenv run':

    pipenv shell
    python initialize.py

Once you're finished, you can run 'exit' to exit the
pipenv shell and return to your normal shell.
pipenv run python initialize.py

[Warning] Failed to find a Team (called "Group" in the Shortcut API) to automatically assign imported stories and epics to.
          If you would like to assign a Team/Group for the stories and epics you import, please:
  1. Review the Shortcut Teams/Groups printed below (also written to data/shortcut_groups.csv for reference).
  2. Copy the numeric ID of your desired Team/Group (group_id column in the CSV).
  3. Paste it as the "group_id" value in your config.json file.
  4. Rerun initialize.py.

Shortcut Teams/Groups
=====================
Group/Team 66105996-75ed-46b7-9162-319ba972e83f : "Team One"


[Success] Pivotal Tracker export and local configuration have been validated.
pipenv run python pivotal_import.py
[Note] This importer adheres to the Shortcut API rate limit of 200 requests per minute.
       It may pause for up to 70 seconds during processing to avoid request throttling.
Summary of data to be imported
  - Labels : 1
  - Stories : 3
Creating 0 pivotal->shortcut 2024-04-16 16:13
Import Started

Visit https://example.com/entity/0 to monitor import progress
Finished creating 0 epics
Creating 1 Alpha Feature
Creating 2 Gamma Radiation!
Creating 3 Beta Feature
Finished creating 3 stories
```

Thanks in advance for any further info you're able to share!

**Comment by semperos** [comment]
Happy to reopen this issue and continue supporting. Until we hear back with more details to reproduce, I'm closing this issue for now.

**Comment by davydotcom** [comment]
@semperos thanks I believe you met with one of our colleagues and resolved it!
